---
hide_body: false
is_partial: false
fields:
- type: text
  name: productid
  label: ProductId
  config:
    required: true
- type: textarea
  config:
    wysiwyg: true
    schema:
      format: markdown
  label: Säljtext
  name: saltetext
